export const GENERATE_RANDOM_TEXT = "GENERATE_RANDOM_TEXT"
export const GENERATE_RANDOM_TEXT_SUCCESS = "GENERATE_RANDOM_TEXT_SUCCESS"
export const GENERATE_RANDOM_TEXT_FAILED = "GENERATE_RANDOM_TEXT_FAILED"